name: Ansible Deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

permissions:
  contents: read
  packages: read   # allow pulling job container from GHCR

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Pull Ansible container
        run: docker pull ghcr.io/${{ github.repository }}/ansible-docker:ansible

      - name: Run Ansible in container with host network
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e ANSIBLE_SSH_KEY="${{ secrets.ANSIBLE_SSH_KEY }}" \
            ghcr.io/${{ github.repository }}/ansible-docker:ansible \
            bash -c "
              mkdir -p ~/.ssh
              echo \"\$ANSIBLE_SSH_KEY\" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              ansible-playbook ci-ansible/inventory.yml --private-key ~/.ssh/id_ed25519 playbook.yml
            "
