name: Ansible Deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

permissions:
  contents: read
  packages: read   # allow pulling job container from GHCR

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Ansible container
        run: docker pull ghcr.io/${{ github.repository }}:ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_ED25519_ANSIBLE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run Ansible in container with host network
        run: |
          docker run --network host \
          --workdir /workspace \
          -v ${{ github.workspace }}:/workspace \
          -v ~/.ssh:/root/.ssh \
          ghcr.io/${{ github.repository }}:ansible \
          sh -c "cd ci-ansible && ansible-playbook --inventory inventory.yml --private-key /root/.ssh/id_ed25519 --diff playbook.yml"
