name: Ansible Deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

permissions:
  contents: read

jobs:
  run-ansible:
    runs-on: dockerbuild
    container:
      image: ghcr.io/${{ github.repository }}/ansible-docker:ansible
      options: --workdir /workspace   # Default working dir in container
      volumes:
        - ${{ github.workspace }}:/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout repo (this happens outside, then files are mounted inside the container)
      - uses: actions/checkout@v4

      # Run ansible-playbook (inside the container)
      - name: Run Ansible Playbook
        run: |
          cd  ci-ansible && ansible-playbook --inventory inventory.yml --diff playbook.yml
