name: Ansible Deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]

permissions:
  contents: read
  packages: read   # allow pulling job container from GHCR

jobs:
  run-ansible:
    # if you don't have a self-hosted runner named "dockerbuild", use ubuntu-latest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:ansible
      options: --workdir /workspace
      volumes:
        - ${{ github.workspace }}:/workspace
      
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_ED25519_ANSIBLE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - uses: actions/checkout@v4
      - name: Run Ansible Playbook
        run: |
          cd ci-ansible
          ansible-playbook --inventory inventory.yml --diff playbook.yml --private-key ~/.ssh/id_ed25519
